version: '3'

services:
  proxy:
    image: softy-pinko-proxy:task5
    build:
      context: ./proxy
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - back-end
      - front-end

  back-end:
    image: softy-pinko-back-end:task5
    build:
      context: ./back-end
      dockerfile: Dockerfile

  front-end:
    image: softy-pinko-front-end:task5
    build:
      context: ./front-end
      dockerfile: Dockerfile
    depends_on:
      - back-end
